Attribute VB_Name = "M_SQL_ERROR_HANDLING"
'====================================================================================================================================================
'====================================...SQL Error Handling
'====================================================================================================================================================
Sub S_THONG_BAO_LOI()
    Dim msg As String
'    Debug.Print Err.Number & "<< Ma Loi"
    msg = " - Error #: " & Str(Err.Number) & " ==> (Ma loi)" & Chr(13) & _
            " - Was generated by: " & Err.Source & " ==> (Chuong trinh bao loi)" & Chr(13) & _
            " - Error Line: " & Erl & Chr(13) & _
            " - Error Desciption: " & Err.Description
    MsgBox msg, , "Error", Err.HelpFile, Err.HelpContext
End Sub
Sub S_XU_LY_LOI()
    If Err.Number = -2147217873 Then
        MsgBox "Huong dan: Da bi trung ID, vui long thay doi ID"
    End If
    If Err.Number = -2147217865 Then
        MsgBox "Huong dan: Khong tim thay ten bang trong SQL, vui long sua lai ten bang"
    End If
    If Err.Number = -2147217887 Then
        MsgBox "Huong dan: Kieu du lieu import khong dung quy dinh cua Table"
    End If
    If Err.Number = 3265 Then
        MsgBox "Huong dan: khong tim thay gia tri de thuc hien lenh"
    End If
    If Err.Number = -2147217900 Then
        MsgBox "Huong dan: Loi cau lenh SQL, can phai sua lai"
    End If
    If Err.Number = 3704 Then
        MsgBox "Huong dan: closet da bi dong, kiem tra lai code"
    End If
    If Err.Number = 6 Then
        MsgBox "Huong dan: Tran bo nho"
    End If
    If Err.Number = 91 Then
        MsgBox "Huong dan: Khong co du lieu IMPORT"
    End If
End Sub

